//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user1
    {
        [DisplayName("ID")]
        [Required(ErrorMessage = "** Id is Mandatory")]
        public int id { get; set; }

        [DisplayName("NAME")]
        [Required(ErrorMessage = "** Name is Mandatory")]
      // [StringLength(50, MinimumLength = 3, ErrorMessage = "** Name should be under 3 to 50")]
        public string name { get; set; }

        [DisplayName("PASSWORD")]
        [Required(ErrorMessage = "** Employee Password is mandatory")]
       // [RegularExpression(@"(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$", ErrorMessage = "** UpperCase,LowerCase,Numbers,Symbols,8 Characters")]
        [DataType("Password")]
        public string password { get; set; }

        [DisplayName("EMAIL")]
       // [Required(ErrorMessage = "** Email is Required")]
       // [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[--9a-zA-Z])+@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "** Invalid Email")]
        public string email { get; set; }
    }
}
